%YAML 1.2
---
title: Schema for camera_config_pixel model parameter
version: 0.1.0
base_schema: simpipe-schema
base_schema_url: https://github.com/gammasim/workflows/schema/jsonschema.yml
base_schema_version: 0.1.0
name: camera_config_pixel
developer_note: |-
  Part of sim_telarray camera_config_file (parameter Pixel).
  The entries of pixel_type_id depend on the values provided by
  camera_config_pixel_type.
description: |-
  Definition of pixel types, positions, status (on/off), relative gain
  (w.r.t the provided gain) and quantum/photodetector efficiency
  scaling (scale the provided quantum/photodetector efficiency distribution,
  ignoring wavelength dependence).
data:
  - type: datatable
    table_columns:
      - name: pixel_id
        type: uint
        description: Pixel number (starting at 0)
        required: true
        units: dimensionless
      - name: pixel_type_id
        type: uint
        description: Pixel type ID (see definition in pixel_type)
        required: true
        units: dimensionless
      - name: position_x
        description: Projected pixel x coordinate (in cm) before camera rotation.
        type: double
        units: cm
        required: true
      - name: position_y
        description: Projected pixel y coordinate (in cm) before camera rotation.
        type: double
        units: cm
        required: true
      - name: module_number
        description: |-
          Module number to which the pixel belongs.
          Defines geometry and is used e.g. for pixel alignment with
          PIXELS_PARALLEL=2)
        type: uint
        units: dimensionless
        required: false
        default: 0
      - name: board_number
        description: Board number to which the pixel belongs.
        type: uint
        units: dimensionless
        required: false
        default: 0
      - name: channel_number
        description: |-
          Input channel on electronic board; may be used in
          future version for electronic cross-talk.
        type: uint
        units: dimensionless
        required: false
        default: 0
      - name: module_id
        developer_note: Required to be a hex number in sim_telarray
        description: |-
          Module id to which the pixel belongs.
          If a module is swapped into a different place in the camera, its
          module number (defined by geometry) would change, along with all
          pixel coordinates, but the module ID would remain.
          Not currently used. Should be hexadecimal, starting with 0x.
        type: string
        units: dimensionless
        required: false
        default: 0
      - name: onflag
        description: Turn on or off this pixel
        type: boolean
        default: true
        required: false
        units: dimensionless
      - name: qe_relative
        description: |-
          Scaling factor of the Quantum or photon-detection efficiency of
          this pixel. This scales the provided QE distribution without
          changing the wavelength dependence before any random fluctuations
          are applied.
        type: double
        default: 1.0
        required: false
        units: dimensionless
      - name: gain_relative
        description: |-
          Signal gain or amplification in pixel relative to average
          before any random fluctuations are applied.
        type: double
        default: 1.0
        required: false
        units: dimensionless
      - name: d_z
        description: |-
          Shift of pixel height w.r.t. nominal focal surface shape
          (or module) in centimeters, positive towards the infalling light.
          No shift is needed where pixels are aligned module-wise.
        type: double
        default: 0.0
        required: false
        units: dimensionless
      - name: pixel_rotation
        description: Pixel rotation angle
        type: double
        units: deg
        default: 0.0
        required: false
      - name: n_x
        developer_note: Must be zero for pixels_parallel==1 or pixels_parallel==2.
        description: |-
          X component of non-standard pointing direction of
          pixel axis is indicated by vector (Nx, Ny, 1.0).
        type: double
        units: deg
        default: 0.0
        required: false
      - name: n_y
        developer_note: Must be zero for pixels_parallel==1 or pixels_parallel==2.
        description: |-
          Y component of non-standard pointing direction of
          pixel axis is indicated by vector (Nx, Ny, 1.0).
        type: double
        units: deg
        default: 0.0
        required: false
instrument:
  class: Camera
  type:
    - LSTCam
    - FlashCam
    - NectarCam
    - SSTCam
    - SCTCam
activity:
  setting:
    - SetParameterFromExternal
  validation:
    - ValidateCameraGeometry
    - ValidatePixelStatus
    - ValidateCameraGainsAndEfficiency
source:
  - Initial instrument setup
  - Calibration
  - Observation execution
simulation_software:
  - name: sim_telarray
