%YAML 1.2
---
title: Schema for camera_config_pixel_type model parameter
version: 0.1.0
meta_schema: simpipe-schema
meta_schema_url: https://raw.githubusercontent.com/gammasim/simtools/main/simtools/schemas/data.metaschema.yml
meta_schema_version: 0.1.0
name: camera_config_pixel_type
developer_note: Part of sim_telarray camera_config_file (parameter PixType).
description: |-
  Defines a pixel type, including the geometrical shape (circular, square,
  hexagonal) of the pixel border and of the visible cathode, the size,
  the depth of light collecting elements (funnels) and their reflectivity
  (as a number) or angular acceptance (as a file name).
short_description: Pixel type definition.
data:
  - type: datatable
    table_columns:
      - name: pixel_type_id
        type: uint
        description: Pixel type ID.
        default: 1
        required: true
        units: dimensionless
      - name: photodetector_type_id
        type: uint
        description: Photodetector type id;
        default: 0
        units: dimensionless
        required: true
      - name: cathode_shape
        description: "'Cathode shape, 0: circ., 1: hex(flat x), 2: sq., 3: hex(flat\
          \ y).'"
        type: uint
        allowed_range:
          min: 0
          max: 3
        units: dimensionless
        required: true
      - name: cathode_diameter
        description: |-
          Cathode diameter.
          (not used when tabled light guide efficiency is provided).
        type: double
        units: cm
        required: false
      - name: pixel_shape
        description: "'Pixel shape, 0: circ., 1: hex(flat x), 2: sq., 3: hex(flat\
          \ y).'"
        type: uint
        allowed_range:
          min: 0
          max: 3
        units: dimensionless
        required: true
      - name: pixel_diameter
        description: Pixel diameter.
        type: double
        units: cm
        required: true
      - name: funnel_depth
        description: |-
          Funnel depth
          (not used when tabled light guide efficiency is provided).
        type: double
        default: 0.0
        units: cm
        required: false
        condition: lightguide_efficiency_vs_incident_angle==None
      - name: pixel_transparency
        description: Pixel transparency.
        type: double
        units: dimensionless
        allowed_range:
          min: 0.0
          max: 1.0
        required: false
      - name: funnel_wall_reflectivity
        description: |-
          Pixel (funnel) wall reflectivity (averaged over
          typical incident angles).
        type: double
        units: dimensionless
        allowed_range:
          min: 0.0
          max: 1.0
        required: false
instrument:
  class: Camera
  type:
    - LSTCam
    - FlashCam
    - NectarCam
    - SSTCam
    - SCTCam
activity:
  setting:
    - SetParameterFromExternal
  validation:
    - ValidateParameterByExpert
    - ValidateCameraGeometry
    - ValidateTelescopeEfficiency
    - ValidateTelescopeSimulationModel
source:
  - Initial instrument setup
simulation_software:
  - name: sim_telarray
